### ISSUE TITLE
Conditions with attribute comparison

### ISSUE THREAD

**Issue by briananderton-il** [AllocZero/EfficientDynamoDb#160]
When attempting to build a condition comparing to another attribute as the documentation shows, like this:

```
var candidate = ...
var scopeWrite = Transact.UpdateItem<JobScope>()
  .WithPrimaryKey(pk, sk)
  .WithCondition(Condition<JobScope>.OnSizeOf(js => js.Jobs).LessThan(js => js.MaxJobs))
  .On(js => js.Jobs).Insert(new HashSet<string> { candidate });
```
the **`LessThan`** method gives a compile error: 

`error CS1660: Cannot convert lambda expression to type 'Expression' because it is not a delegate type`

Am I doing something wrong?  The parameter is of type **`Expression`** - should this be **`Expression<Func<TEntity, TProperty>>`**?

**Comment by briananderton-il** [comment]
Seems to work well, thanks.    However, I did experience a related problem when using a constant integer instead of an expression in the `LessThan` method.   I get this exception:

```
15:46:53.8491544 ERR DeveloperExceptionPageMiddleware-> An unhandled exception has occurred while executing the request.System.InvalidCastException: Unable to cast object of type 'EfficientDynamoDb.Internal.Converters.Collections.StringSetDdbConverter`1[System.String]' to type 'EfficientDynamoDb.Converters.DdbConverter`1[System.Int32]'.
   at EfficientDynamoDb.FluentCondition.Core.FilterBase`1.GetPropertyConverter[TProperty](DdbExpressionVisitor visitor)
   at EfficientDynamoDb.FluentCondition.Operators.Common.FilterLessThan`2.WriteAttributeValues(DdbWriter& writer, DynamoDbContextMetadata metadata, Int32& valuesCount, DdbExpressionVisitor visitor)
   at EfficientDynamoDb.Internal.Extensions.Utf8JsonWriterExtensions.WriteUpdates(DdbWriter& ddbWriter, DynamoDbContextMetadata metadata, NoAllocStringBuilder& builder, DdbExpressionVisitor visitor, BuilderNode firstUpdateNode, BuilderNode lastUpdateNode, Boolean hasAdd, Boolean hasSet, Boolean hasRemove, Boolean hasDelete, FilterBase updateCondition)
   at EfficientDynamoDb.Internal.Extensions.Utf8JsonWriterExtensions.WriteUpdateItem(DdbWriter& ddbWriter, DynamoDbContextConfig config, NoAllocStringBuilder& builder, DdbExpressionVisitor visitor, DdbClassInfo classInfo, BuilderNode node, Int32& writeState)
   at EfficientDynamoDb.Internal.Operations.UpdateItem.UpdateItemHighLevelHttpContent.WriteUpdateItem(DdbWriter& ddbWriter, Int32& writeState)
   at EfficientDynamoDb.Internal.Operations.UpdateItem.UpdateItemHighLevelHttpContent.WriteDataAsync(DdbWriter ddbWriter)
   at EfficientDynamoDb.Internal.Operations.Shared.DynamoDbHttpContent.SerializeToStreamAsync(Stream stream, TransportContext context)
   at EfficientDynamoDb.Internal.Operations.Shared.DynamoDbHttpContent.SerializeToStreamAsync(Stream stream, TransportContext context)
   at EfficientDynamoDb.Internal.Operations.Shared.DynamoDbHttpContent.CreatePooledContentReadStreamAsync()
   at EfficientDynamoDb.Internal.HttpApi.SendAsync(DynamoDbContextConfig config, HttpContent httpContent, CancellationToken cancellationToken)
   at EfficientDynamoDb.DynamoDbContext.UpdateItemAsync[TEntity](DdbClassInfo classInfo, BuilderNode node, CancellationToken cancellationToken)
   at EfficientDynamoDb.Operations.UpdateItem.UpdateEntityRequestBuilder`1.ToItemAsync(CancellationToken cancellationToken)
   at JobRunner.Data.DynamoJobQueue.TestAsync(CancellationToken ct) in C:\ILE\universal-job-runner\JobRunner.Data\Queue\DynamoJobQueue.cs:line 184
```

**Comment by firenero** [comment]
@briananderton-il This one seems unrelated to the original API issue. And I can't easily reproduce it. 
Do you mind creating a separate issue and providing some code for me to reproduce?

**Comment by briananderton-il** [comment]
@firenero - no problem, done.
