### ISSUE TITLE
InvalidCastException using OnSizeOf condition with LessThan operator with integer parameter

### ISSUE THREAD

**Issue by briananderton-il** [AllocZero/EfficientDynamoDb#162]
I created a simple reproducible sample demonstrating an **`InvalidCastException`**  that occurs when using an **`OnSizeOf`** condition and the **`LessThan`** operator with an integer (rather than an expression) parameter.

```
using System.Collections.Generic;
using System.Threading.Tasks;
using Amazon.Runtime;
using EfficientDynamoDb;
using EfficientDynamoDb.Attributes;
using EfficientDynamoDb.Configs;
using EfficientDynamoDb.Credentials.AWSSDK;

namespace ConsoleApp1
{
	class Program
	{
		static async Task Main(string[] args)
		{
			var credentials = FallbackCredentialsFactory.GetCredentials();
			var region = FallbackRegionFactory.GetRegionEndpoint();
			var config = new DynamoDbContextConfig(RegionEndpoint.Create(region.SystemName), credentials.ToCredentialsProvider());
			var context = new DynamoDbContext(config);

			await context.PutItem()
				.WithItem(new Scope { Name = "123", Jobs = new HashSet<string> {"0"}})
				.ExecuteAsync();

			const int maxSize = 2;
			for (var i = 1; i < 10; i++)
			{
				await context.UpdateItem<Scope>()
					.WithCondition(Condition<Scope>.OnSizeOf(scope => scope.Jobs).LessThan(maxSize))
					.On(scope=>scope.Jobs).Insert(new HashSet<string> { i.ToString() })
					.ExecuteAsync();
			}
		}
	}

	[DynamoDbTable("onsizeoftest")]
	public class Scope
	{
		[DynamoDbProperty(nameof(Name), DynamoDbAttributeType.PartitionKey)] 
		public string Name { get; init; }

		[DynamoDbProperty(nameof(Jobs))]
		public HashSet<string> Jobs { get; init; }
	}
}

```

And here is the exception I get:

```
Unhandled exception. System.InvalidCastException: Unable to cast object of type 'EfficientDynamoDb.Internal.Converters.Collections.StringSetDdbConverter`1[System.String]' to type 'EfficientDynamoDb.Converters.DdbConverter`1[System.Int32]'.
   at EfficientDynamoDb.FluentCondition.Core.FilterBase`1.GetPropertyConverter[TProperty](DdbExpressionVisitor visitor)
   at EfficientDynamoDb.FluentCondition.Operators.Common.FilterLessThan`2.WriteAttributeValues(DdbWriter& writer, DynamoDbContextMetadata metadata, Int32& valuesCount, DdbExpressionVisitor visitor)
   at EfficientDynamoDb.Internal.Extensions.Utf8JsonWriterExtensions.WriteUpdates(DdbWriter& ddbWriter, DynamoDbContextMetadata metadata, NoAllocStringBuilder& builder, DdbExpressionVisitor visitor, BuilderNode firstUpdateNode, BuilderNode lastUpdateNode, Boolean hasAdd, Boolean hasSet, Boolean hasRemove, Boolean hasDelete, FilterBase updateCondition)
   at EfficientDynamoDb.Internal.Extensions.Utf8JsonWriterExtensions.WriteUpdateItem(DdbWriter& ddbWriter, DynamoDbContextConfig config, NoAllocStringBuilder& builder, DdbExpressionVisitor visitor, DdbClassInfo classInfo, BuilderNode node, Int32& writeState)
   at EfficientDynamoDb.Internal.Operations.UpdateItem.UpdateItemHighLevelHttpContent.WriteUpdateItem(DdbWriter& ddbWriter, Int32& writeState)
   at EfficientDynamoDb.Internal.Operations.UpdateItem.UpdateItemHighLevelHttpContent.WriteDataAsync(DdbWriter ddbWriter)
   at EfficientDynamoDb.Internal.Operations.Shared.DynamoDbHttpContent.SerializeToStreamAsync(Stream stream, TransportContext context)
   at EfficientDynamoDb.Internal.Operations.Shared.DynamoDbHttpContent.SerializeToStreamAsync(Stream stream, TransportContext context)
   at EfficientDynamoDb.Internal.Operations.Shared.DynamoDbHttpContent.CreatePooledContentReadStreamAsync()
   at EfficientDynamoDb.Internal.HttpApi.SendAsync(DynamoDbContextConfig config, HttpContent httpContent, CancellationToken cancellationToken)
   at EfficientDynamoDb.DynamoDbContext.UpdateItemAsync[TEntity](DdbClassInfo classInfo, BuilderNode node, CancellationToken cancellationToken)
   at EfficientDynamoDb.Operations.UpdateItem.UpdateEntityRequestBuilder`1.ToItemAsync(CancellationToken cancellationToken)
   at ConsoleApp1.Program.Main(String[] args) in C:\ILE\universal-job-runner\ConsoleApp1\Program.cs:line 27
   at ConsoleApp1.Program.<Main>(String[] args)
```

**Comment by firenero** [comment]
@briananderton-il fixed in 0.9.13-alpha.0.2
