### ISSUE TITLE
Value null at 'tableName' failed to satisfy constraint: Member must not be null

### ISSUE THREAD

**Issue by josephj-acmo** [AllocZero/EfficientDynamoDb#164]
I am getting the error "ValidationException: 1 validation error detected: Value null at 'tableName' failed to satisfy constraint: Member must not be null EfficientDynamoDb.Internal.ErrorHandler.ProcessErrorAsync(DynamoDbContextMetadata metadata, HttpResponseMessage response, CancellationToken cancellationToken)"

`DynamoDbContext _context = new DynamoDbContext(new DynamoDbContextConfig(AWSConfig.REGION, new EfficientDynamoDb.Configs.AwsCredentials(@"<access-key>", @"<secret-key>")));
            var item = await _context.GetItemAsync<EntityName>(@"SYSTEM", @"ALLOWEDCOLOURS");`

I have also added the attribute "[DynamoDbTable("EntityName")]" to the entity class definition.
Could you please advise what is missing? Thanks.

**Comment by lezzi** [comment]
Hey @josephj-acmo. May I ask you to share your entity class?

**Comment by josephj-acmo** [comment]
Hi Iezzi,
Sure, please find below:
`[DynamoDbTable("DataTable")]
public class System
{
    [DynamoDbProperty("PK", DynamoDbAttributeType.PartitionKey)]
    public string PK { get; set; }

    [DynamoDbProperty("SK", DynamoDbAttributeType.SortKey)]
    public string SK { get; set; }

    [DynamoDbProperty("RecordType")]
    public string RecordType { get; set; }

    [DynamoDbProperty("RecordInfo")]
    public string Colours { get; set; }
}`

Could you please confirm if this library can be used with Lambda functions developed on .Net Core? Is there a sample project that you can share as we have been trying to figure out how to return/cast the "items" returned by Query method from the Web API controller? Thanks for your help.

**Comment by lezzi** [comment]
Hmm, everything looks correct. The only way this validation error can happen is if the `DynamoDbTable` attribute is not applied. If possible, may I ask you to upload a test app where you can consistently get this error?

> Could you please confirm if this library can be used with Lambda functions developed on .Net Core?
Yes, you can use the library with Lambda functions.

>  how to return/cast the "items" returned by Query method from the Web API controller
You can check our example from the docs https://alloczero.github.io/EfficientDynamoDb/docs/dev_guide/dev-guide/high-level/read#querying-data

For example, after calling `ToListAsync`, you get the list of entities (classes), which you can either return in the controller or map to some DTO class.

**Comment by josephj-acmo** [comment]
Thanks for your feedback.
It appears the issue was related to browser caching my previous build, and opening the browser in incognito mode seems to no longer giving me the error reported.

Unfortunately I am now getting a different error though, when calling the GetItemAsync method as below:
`        public async IAsyncEnumerable<System> GetAllowedSystemColoursAsync()
        {
            var item = await _context.GetItemAsync<System>("SYSTEM", "ALLOWEDCOLOURS");
            yield return item;
        }`

The error is:
`System.InvalidOperationException: Cannot get the value of a token type 'StartArray' as a string.
   at System.Text.Json.Utf8JsonReader.GetString()
   at EfficientDynamoDb.Internal.Converters.Primitives.StringDdbConverter.Read(DdbReader& reader)
   at EfficientDynamoDb.Internal.Metadata.DdbPropertyInfo`1.TryReadAndSetMember(Object obj, DdbReader& reader)
   at EfficientDynamoDb.Internal.Converters.ObjectDdbConverter`1.TryRead(DdbReader& reader, T& value)
   at EfficientDynamoDb.Internal.Metadata.DdbPropertyInfo`1.TryReadAndSetMember(Object obj, DdbReader& reader)
   at EfficientDynamoDb.Internal.Converters.Json.JsonObjectDdbConverter`1.TryRead(DdbReader& reader, T& value, Boolean isRoot)
   at EfficientDynamoDb.Internal.Converters.Json.JsonObjectDdbConverter`1.TryReadRoot(DdbReader& reader, T& value)
   at EfficientDynamoDb.Internal.Reader.EntityDdbJsonReader.ReadCore[T](DdbReader& reader)
   at EfficientDynamoDb.Internal.Reader.EntityDdbJsonReader.ReadCore[T](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, DdbEntityReadStack& readStack)
   at EfficientDynamoDb.Internal.Reader.EntityDdbJsonReader.ReadAsync[TEntity](Stream utf8Json, DdbClassInfo classInfo, DynamoDbContextMetadata metadata, Boolean returnCrc, Int32 defaultBufferSize, CancellationToken cancellationToken)
   at EfficientDynamoDb.DynamoDbContext.ReadAsync[TResult](HttpResponseMessage response, CancellationToken cancellationToken)
   at EfficientDynamoDb.DynamoDbContext.ReadAsync[TResult](HttpResponseMessage response, CancellationToken cancellationToken)
   at EfficientDynamoDb.DynamoDbContext.GetItemAsync[TEntity](Object partitionKey, Object sortKey, CancellationToken cancellationToken)
   at com.acmo.wmc.api.Utilities.SystemHelper.GetAllowedSystemColoursAsync()+MoveNext() in C:\Users\josephj\source\repos\wmc.function\WMC-Serverless-API\WMC-Serverless-API\Utilities\SystemHelper.cs:line 23
   at com.acmo.wmc.api.Utilities.SystemHelper.GetAllowedSystemColoursAsync()+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.AsyncEnumerableReader.ReadInternal[T](Object value)
   at Microsoft.AspNetCore.Mvc.Infrastructure.AsyncEnumerableReader.ReadInternal[T](Object value)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor.ExecuteAsyncEnumerable(ActionContext context, ObjectResult result, Object asyncEnumerable, Func`2 reader)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultFilters>g__Awaited|27_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)`

**Comment by lezzi** [comment]
Hey @josephj-acmo, I suspect that one of your property types is either wrong or you need a custom converter. Most likely you used a string instead of an array, it depends on what kind of data is stored in the DynamoDb. If you can show me an example value from the DynamoDb console, I can help you out.

**Comment by josephj-acmo** [comment]
Thanks Iezzi,
That was very valuable feedback, and it seems to be due to the fact that the DynamoDB attribute was of type "List" while I had in the entity class in C# defined as string. Could you please confirm if I need to use a CustomConverter to map the list DynamoDB List attribute to C# property?

`"TableData": [
  {
    "PK": {
      "S": "SYSTEM"
    },
    "SK": {
      "S": "ALLOWEDCOLOURS"
    },
    "RecordType": {
      "S": "AllowedColours"
    },
    "RecordInfo": {
      "L": [
        {
          "S": "213338"
        },
        {
          "S": "146E87"
        }
      ]
    }
  }`

Above mentioned is a sample record (exported out of NoSQL work bench as JSON) that I am trying to retrieve and the column of interest is the RecordInfo. Any inputs will be highly appreciated. Thanks.

**Comment by lezzi** [comment]
You need to just make the `Colours` property a collection type. For example, it can be a `List<string>` or a `string[]` array.

```
[DynamoDbProperty("RecordInfo")]
public List<string> Colours { get; set; }
```

**Comment by josephj-acmo** [comment]
Wonderful, that helped fix the issue. Thank you very much!
