### ISSUE TITLE
OverflowException: Value was either too large or too small for an unsigned byte.

### ISSUE THREAD

**Issue by zbyszekpy** [AllocZero/EfficientDynamoDb#194]
LongDdbConverter (and few others) contains incorrect number conversion 

System.OverflowException: Value was either too large or too small for an unsigned byte.
   at System.Number.ThrowOverflowException(TypeCode type)
   at System.Byte.Parse(String s, IFormatProvider provider)
   at EfficientDynamoDb.DocumentModel.NumberAttributeValue.ToByte()
   at EfficientDynamoDb.Internal.Converters.Primitives.Numbers.LongDdbConverter.Read(AttributeValue& attributeValue)
   at EfficientDynamoDb.Internal.Metadata.DdbPropertyInfo`1.SetValue(Object obj, AttributeValue& attributeValue)
   at EfficientDynamoDb.Internal.Extensions.DocumentExtensions.ToObject[T](Document document, DynamoDbContextMetadata metadata)
   at EfficientDynamoDb.DynamoDbContext.ToObject[T](Document document)

To reproduce problem model should contains long field with value higher than byte range

I will create PR with bugfix in few minutes

**Comment by zbyszekpy** [comment]
@lezzi Could you publish nuget with  https://github.com/AllocZero/EfficientDynamoDb/pull/195 ?
Thank you
