### ISSUE TITLE
LocalSecondaryIndex  query returning Object Reference not set to an instance of an object

### ISSUE THREAD

**Issue by funkel1989** [AllocZero/EfficientDynamoDb#202]
Here is the error i'm getting
```
at EfficientDynamoDb.Internal.Operations.Query.QueryHighLevelHttpContent.WriteCondition(Utf8JsonWriter writer, FilterBase filterBase, NoAllocStringBuilder& builder, DdbExpressionVisitor visitor, Int32& valuesCount, String propertyName)
   at EfficientDynamoDb.Internal.Operations.Query.QueryHighLevelHttpContent.WriteExpressions(DdbWriter& writer, BuilderNode node)
   at EfficientDynamoDb.Internal.Operations.Query.QueryHighLevelHttpContent.WriteDataAsync(DdbWriter ddbWriter)
   at EfficientDynamoDb.Internal.Operations.Shared.DynamoDbHttpContent.SerializeToStreamAsync(Stream stream, TransportContext context)
   at EfficientDynamoDb.Internal.Operations.Shared.DynamoDbHttpContent.SerializeToStreamAsync(Stream stream, TransportContext context)
   at EfficientDynamoDb.Internal.Operations.Shared.DynamoDbHttpContent.CreatePooledContentReadStreamAsync()
   at EfficientDynamoDb.Internal.HttpApi.SendAsync(DynamoDbContextConfig config, HttpContent httpContent, CancellationToken cancellationToken)
   at EfficientDynamoDb.DynamoDbContext.QueryListAsync[TEntity](String tableName, BuilderNode node, CancellationToken cancellationToken)
   at EfficientDynamoDb.Operations.Query.QueryEntityRequestBuilder`1.ToListAsync(CancellationToken cancellationToken)
   at DataAccess.Repositories.GenericRepository`1.ListByIdFromIndex[TIndex](FilterBase condition, TIndex index) in D:\code\git\battleline\FrontlineCrm.Api\DataAccess\Repositories\GenericRepository.cs:line 59
   at DataAccess.DbServices.ScheduleDbService.AppendUser(Schedule schedule) in D:\code\git\battleline\FrontlineCrm.Api\DataAccess\DbServices\ScheduleDbService.cs:line 73
```

```C#
public async Task<List<TEntity>> ListByIdFromIndex<TIndex>(FilterBase condition, TIndex index) where TIndex : Enum
    {
        // This is the line that throws the above error.  
        var queryResult = await _context.Query<TEntity>().FromIndex(nameof(index)).WithFilterExpression(condition)
            .ToListAsync();

        return queryResult.Any() ? new List<TEntity>() : queryResult.ToList();
    }

private async Task AppendUser(Schedule schedule)
    {
        var filter = Condition.ForEntity<DynamoDbUser>();

        var condition = Joiner.And(
            filter.On(x => x.SourceSystemId).EqualTo(schedule.SourceSystemId.ToString()),
            filter.On(x => x.ScheduleId).EqualTo(schedule.Id.ToString())
        );
        
        var users = await _dbUserRepo.ListByIdFromIndex(condition, UserIndex.LSISchedule);

        if (users.Any())
        {
            schedule.Users = _mapper.Map<List<User>>(users);
        }
    }

[DynamoDbTable("Users")]
public class DynamoDbUser : IDynamoEntity
{
    [DynamoDbProperty(nameof(SourceSystemId), DynamoDbAttributeType.PartitionKey)]
    public string SourceSystemId { get; set; } = string.Empty;
    
    [DynamoDbProperty(nameof(Id), DynamoDbAttributeType.SortKey)]
    public string Id { get; set; } = string.Empty;

    public UserRole Role { get; set; }

    [DynamoDbProperty(nameof(ScheduleId))]
    public string? ScheduleId { get; set; }

    [DynamoDbVersion, DynamoDbProperty(nameof(Version))]
    public int? Version { get; set; }
}
```

Not sure what I'm missing here but I'm assuming it's something simple.  Also, I apologize for the duplicate issues here, I think I closed #201 a little too early in testing.

I also tried this but it returned an error saying that the index does not exist, which to me sounds right before the model doesn't define ScheduleId as a sort key because there can only be one sort key.
```c#
public async Task<List<TEntity>> ListByIdFromIndex<TIndex>(FilterBase condition, TIndex index) where TIndex : Enum
    {
        // This is the line that throws the above error.  
        var queryResult = await _context.Query<TEntity>().FromIndex(nameof(index)).WithKeyExpression(condition)
            .ToListAsync();

        return queryResult.Any() ? new List<TEntity>() : queryResult.ToList();
    }
```

**Comment by firenero** [comment]
You're getting the first error because your query missing a `KeyExpression` which is required by DynamoDB. If you want to get data using only `FilterExpression` you have to use `Scan` operation instead of `Query` but it has performance and cost consequences. 

The second version of the code is correct from the DDB perspective but most likely there is a bug in the index name here: `FromIndex(nameof(index))`. It will always pass the name of the variable which is `index` and most likely this index doesn't exist in your configuration. I guess you want to use the enum value as an index name, `index.ToString()` or something similar.

Let me know if that helps.

**Comment by funkel1989** [comment]
yep index.ToString() did it. it's the little things lol. Thanks again for the help, it completely slipped my mind that nameof worked that way. This is all set
