### ISSUE TITLE
Microsoft.IO.RecyclableMemoryStream dependency issue

### ISSUE THREAD

**Issue by alexey62soft** [AllocZero/EfficientDynamoDb#246]
Hey everyone!

It seems EfficientDynamoDb uses an old version of [Microsoft.IO.RecyclableMemoryStream](https://github.com/AllocZero/EfficientDynamoDb/blob/main/src/EfficientDynamoDb/EfficientDynamoDb.csproj#L33). At the same time, some standard packages like [Microsoft.Extensions.Resilience](https://www.nuget.org/packages/Microsoft.Extensions.Resilience) starting from version 8.3.0 uses the latest version of Microsoft.IO.RecyclableMemoryStream (3.0). That causes an implicit upgrade of the Microsoft.IO.RecyclableMemoryStream on the project level and the error on the EfficientDynamoDb side:

> Method not found: 'System.IO.MemoryStream Microsoft.IO.RecyclableMemoryStreamManager.GetStream()'. System.MissingMethodException: Method not found: 'System.IO.MemoryStream Microsoft.IO.RecyclableMemoryStreamManager.GetStream()'.
   at EfficientDynamoDb.Internal.Operations.Shared.DynamoDbHttpContent.CreatePooledContentReadStreamAsync()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at EfficientDynamoDb.Internal.Operations.Shared.DynamoDbHttpContent.CreatePooledContentReadStreamAsync()
   at EfficientDynamoDb.Internal.Operations.Shared.DynamoDbHttpContent.CreateContentReadStreamAsync()
   at System.Net.Http.HttpContent.ReadAsStreamAsync(CancellationToken cancellationToken)
   at EfficientDynamoDb.Internal.HttpApi.SendAsync(DynamoDbContextConfig config, HttpContent httpContent, CancellationToken cancellationToken)
   at EfficientDynamoDb.DynamoDbContext.PutItemAsync[TEntity](BuilderNode node, CancellationToken cancellationToken)
   at EfficientDynamoDb.Operations.PutItem.PutItemEntityRequestBuilder`1.ExecuteAsync(CancellationToken cancellationToken)
   
 Here is the commit of upgrade: https://github.com/dotnet/extensions/commit/34ba23f48ce096f9111eee644c4883dbc51f729d

**Comment by KurbanovD** [comment]
Hi, the same for me
Could you take a look pls @firenero

**Comment by firenero** [comment]
Hi, can you send an example that reproduces this issue? I wasn't able to reproduce it on my side using the Microsoft.Extensions.Resilience v8.5.0.

The `RecyclableMemoryStreamManager.GetStream()` method signature hasn't been changed since v1.3.6 that we use so the issue looks weird.

**Comment by alexey62soft** [comment]
I will prepare and share example with you, @firenero.

**Comment by alexey62soft** [comment]
> I will prepare and share example with you, @firenero.

@firenero, here is an example of .NET 8 AWS Lambda that allows to reproduce exceptions via __Mock Lambda Test Tool__. A default AWS profile on your machine is enough to test. In the archive, you'll find a screenshot of the parameters used to run the lambda and exception itself.

.NET version on my machine - 8.0.204. Also, that is reproducible on the AWS environment (dotnet8).

[TestNet8Lambda.zip](https://github.com/AllocZero/EfficientDynamoDb/files/15369201/TestNet8Lambda.zip)

**Comment by alexey62soft** [comment]
@firenero , do you need anything else from me?

**Comment by alexey62soft** [comment]
@firenero, do you have any update on this one?

**Comment by firenero** [comment]
The fix is available in [v0.9.16](https://www.nuget.org/packages/EfficientDynamoDb/0.9.16)

**Comment by alexey62soft** [comment]
Thanks for the fix, @firenero!
