### ISSUE TITLE
System.IO.InvalidDataException on TransactWrite

### ISSUE THREAD

**Issue by alexey62soft** [AllocZero/EfficientDynamoDb#259]
Hello everyone!

I'm using EfficienDynamoDb v0.9.16 (runtime - **.NET 8**) like that:

```csharp
var updateOperation = _dbContext.TransactWrite()
    .WithClientRequestToken(Guid.NewGuid().ToString())
    .WithItems(CreateTransactItems(/* data is here */))
    .ExecuteAsync(cx);

try
{
    await updateOperation;
}
catch (TransactionCanceledException tcex)
{
    /* Reprocessing is here */
}
```

And recently I started receive the following error is DynamoDB responds with error:

> System.IO.InvalidDataException: The archive entry was compressed using an unsupported compression method.
   at System.IO.Compression.Inflater.Inflate(FlushCode flushCode)
   at System.IO.Compression.Inflater.ReadInflateOutput(Byte* bufPtr, Int32 length, FlushCode flushCode, Int32& bytesRead)
   at System.IO.Compression.Inflater.InflateVerified(Byte* bufPtr, Int32 length)
   at System.IO.Compression.DeflateStream.CopyToStream.WriteAsyncCore(ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.CopyToContentLengthAsync(Stream destination, Boolean async, UInt64 length, Int32 bufferSize, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.ContentLengthReadStream.CompleteCopyToAsync(Task copyTask, CancellationToken cancellationToken)
   at System.IO.Compression.DeflateStream.CopyToStream.CopyFromSourceToDestinationAsync()
   at EfficientDynamoDb.Internal.ErrorHandler.ProcessErrorAsync(DynamoDbContextMetadata metadata, HttpResponseMessage response, CancellationToken cancellationToken)
   at EfficientDynamoDb.Internal.ErrorHandler.ProcessErrorAsync(DynamoDbContextMetadata metadata, HttpResponseMessage response, CancellationToken cancellationToken)
   at EfficientDynamoDb.Internal.ErrorHandler.ProcessErrorAsync(DynamoDbContextMetadata metadata, HttpResponseMessage response, CancellationToken cancellationToken)
   at EfficientDynamoDb.Internal.HttpApi.SendAsync(DynamoDbContextConfig config, HttpContent httpContent, CancellationToken cancellationToken)
   at EfficientDynamoDb.DynamoDbContext.TransactWriteItemsAsync(BuilderNode node, CancellationToken cancellationToken)
   at /* application code mentioned above*/

Can you help me understand the reason for the error? Is that associated with the library itself?

**Update:** setting DecompressionMethods.None [here](https://github.com/AllocZero/EfficientDynamoDb/blob/main/src/EfficientDynamoDb/Configs/Http/DefaultHttpClientFactory.cs#L16) resolves the problem.

**Comment by alexey62soft** [comment]
@firenero, maybe you can take a look on the error?

**Comment by firenero** [comment]
@alexey62soft Seems like something is wrong with gzip decompression during DDB error processing. As you noticed, we use automatic decompression so getting an error there is unusual. But since setting AutomaticDecompressions to None there is definitely something wrong with compression. There are several things we can do to troubleshoot it:
1. Do you only get this exception when processing DynamoDB error? Could you try running a `query` or `scan` request with large response body (larger than 4KB) to test if decompression works for successful operations?
1. Do you get this error consistently with some requests or it's random and can't be reproduced reliably?
1. If you can reproduce it, could you try to put breakpoint to [this line](https://github.com/AllocZero/EfficientDynamoDb/blob/a87109624a0482ce94d69cc8dcea9eb648fc51d1/src/EfficientDynamoDb/Internal/ErrorHandler.cs#L30) and confirm that the response stream is indeed gzip compressed?

**Comment by alexey62soft** [comment]
@firenero First of all, thank you for your response, and sorry for the delay!

> Do you only get this exception when processing DynamoDB errors? Could you try running a query or scan request with a large response body (larger than 4KB) to test if decompression works for successful operations?

I used the query operation that has the response with "Content-Length: 29896 bytes" when "AutomaticDecompression = DecompressionMethods.None". With "AutomaticDecompression = DecompressionMethods.GZip", I still received a successful response with "Content-Length: 1143 bytes" and "Content-Encoding: gzip". No errors - everything was processed correctly.

> Do you get this error consistently with some requests or it's random and can't be reproduced reliably?

I started to receive that issue just a couple of days ago. But I can notice consistent behavior - it always failed on error responses with large "Content-Length" - I used the "ReturnValuesOnConditionCheckFailure.AllOld" setting for transaction items in the code.

> If you can reproduce it, could you try to put a breakpoint to [this line](https://github.com/AllocZero/EfficientDynamoDb/blob/a87109624a0482ce94d69cc8dcea9eb648fc51d1/src/EfficientDynamoDb/Internal/ErrorHandler.cs#L30) and confirm that the response stream is indeed gzip compressed?

Yes, I was able to reproduce that locally using different configurations. I assume the reason of the error - changes in AWS API [request compression support](https://docs.aws.amazon.com/sdkref/latest/guide/feature-compression.html).

### AutomaticDecompression - DecompressionMethods.None

**Response.RequestMessage.Headers**:

1. X-Amz-Date,[20241224T150420Z]
1. x-amz-security-token,[...]
1. Host,[dynamodb.us-east-1.amazonaws.com]
1. Authorization,[...]
1. Transfer-Encoding,[chunked]

**Response.Headers**:

1. Date,[Tue, 24 Dec 2024 14:34:43 GMT]
1. Connection,[keep-alive]
1. x-amzn-RequestId,[...]
1. **x-amz-crc32,[872488556]**

**Response.Content.Type**: System.Net.Http.HttpConnectionResponseContent

**Response.Content.Headers**:

1. Content-Type,[application/x-amz-json-1.0]
1. **Content-Length,[30479]**

**Response.Stream**: **System.Net.Http.HttpConnection.ContentLengthReadStream**

**Result**: Processing is fine. The library was able to process the BadRequest error response.

### AutomaticDecompression = DecompressionMethods.GZip

**Response.Request.Headers**:

1. X-Amz-Date,[20241224T145815Z]
1. x-amz-security-token,[...]
1. Host,[dynamodb.us-east-1.amazonaws.com]
1. Authorization,[...]
1. Transfer-Encoding,[chunked]
1. **Accept-Encoding,[gzip]**

**Response.Headers**:

1. Date,[Tue, 24 Dec 2024 14:27:50 GMT]
1. Connection,[keep-alive]
1. x-amzn-RequestId,[...]
1. **x-amz-crc32,[3431636590]**

**Response.Content.Type**: System.Net.Http.DecompressionHandler.GZipDecompressedContent

**Response.Content.Headers**:

1. Content-Type,[application/x-amz-json-1.0]

**Response.Content.OriginalContent.Headers**:

1. Content-Type,[application/x-amz-json-1.0]
1. **Content-Length,[30479]**
1. **Content-Encoding,[gzip]**

**Response.Stream**: **System.IO.Compression.GZipStream**

**Result:** Processing was failed with System.IO.InvalidDataException provided in the issue description. The library was NOT able to process the BadRequest error response.

### AutomaticDecompression = DecompressionMethods.None, but Accept-Encoding = gzip (manually provided on the request in EfficientDynamoDb.Internal.HttpApi)

**Response.RequestMessage.Headers**:

1. **Accept-Encoding,[gzip]**
1. X-Amz-Date,[20241224T150946Z]
1. x-amz-security-token,[...]
1. Host,[dynamodb.us-east-1.amazonaws.com]
1. Authorization,[...]
1. Transfer-Encoding,[chunked]

**Response.Headers**:

1. Date,[Tue, 24 Dec 2024 15:10:04 GMT]
1. Connection,[keep-alive]
1. x-amzn-RequestId,[...]
1. **x-amz-crc32,[3431636590]**

**Response.Content.Type**: System.Net.Http.HttpConnectionResponseContent

**Response.Content.Headers**:

1. Content-Type,[application/x-amz-json-1.0]
1. **Content-Length,[30479]**
1. **Content-Encoding,[gzip]**

**Response.Stream**: **System.Net.Http.HttpConnection.ContentLengthReadStream**

**Result:** Processing is fine. The library was able to process the BadRequest error response **without additional decompression**.

**Comment by firenero** [comment]
Hi @alexey62soft, could you try [v0.9.17](https://www.nuget.org/packages/EfficientDynamoDb/0.9.17) and check if this issue is fixed in the new version?

**Comment by alexey62soft** [comment]
> Hi [@alexey62soft](https://github.com/alexey62soft), could you try [v0.9.17](https://www.nuget.org/packages/EfficientDynamoDb/0.9.17) and check if this issue is fixed in the new version?

Sure! I pulled latest changes from the repository and retested the case. Unfortunately, the issue is still reproduceable and not resolved.

PS The change was not affecting my use case at all because the position was already set to 0 before.
![Image](https://github.com/user-attachments/assets/ba586373-065c-497f-a735-80277aed2614)

**Comment by firenero** [comment]
Hey @alexey62soft, I've finally got back to work on this issue. It's been fixed in new stable version [0.9.19](https://www.nuget.org/packages/EfficientDynamoDb/0.9.19). Thanks for help with troubleshooting it.

Feel free to re-open it if the fix doesn't work for you.

**Comment by alexey62soft** [comment]
Hello, @firenero! It seems the latest version is working as expected. Appreciate your time and effort on this update!

PS It seems the real issue is on AWS side, and we need to adopt our clients for that 🙂
